# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ludobox
email: your-email@domain.com
description: "Une ludothèque de poche avec une collection de jeux à fabriquer soi-même & des ressources autour de la culture ludique et DIY."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ludobox.net" # the base hostname & protocol for your site
twitter_username: asso_dcalk
github_username:  ludobox

# Build settings
markdown: kramdown
